% Prepare metadata

%% Read admin
trial_tab = readtable(admin_file,'Sheet',trial_sheet);
n_rows = height(trial_tab);

% project_path = pwd;

%% Initiate output table

metaVarDef = {... 
    'n_videocams','doublenan';...
    'n_videoframes','doublenan';...
    'videoframe_rate','doublenan';...
    'video_width','doublenan';...
    'video_height','doublenan';...
    'n_megapix','doublenan';...
    'flag_unequal_no_frames','logical';...
    'flag_unequal_frame_rates','logical';...
    'flag_unequal_video_resolutions','logical';...
    'start_theia_processing','string';...
    'end_theia_processing','string';...
    'theia_processing_time','doublenan';...
    'theia_processing_fps','doublenan'...
    };
n_vars=size(metaVarDef,1);

% Initialize table
meta_tab = [trial_tab table('Size',[n_rows n_vars],...
    'VariableTypes',metaVarDef(:,2),'VariableNames',metaVarDef(:,1))];


%% Write output table to Excel sheet

writetable(meta_tab,admin_file,...
    'Sheet',meta_sheet,'WriteMode','overwritesheet');

if verbose
    disp('Done!')
end
